# Generated by Django 6.0.3 on 2026-03-04 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('NLP', 'Natural Language Processing'), ('CV', 'Computer Vision'), ('RL', 'Reinforcment Learning'), ('OTHER', 'Other')], max_length=5)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('PT', 'PyTorch'), ('TF', 'TensorFlow'), ('KRS', 'Keras'), ('OTHER', 'Other')], max_length=5)),
                ('version', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.JSONField()),
            ],
            options={
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('benchmark_date', models.DateTimeField(auto_now_add=True)),
                ('hardware_used', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('license_key', models.CharField(max_length=100)),
                ('download_link', models.URLField()),
            ],
            options={
                'get_latest_by': 'purchase_date',
            },
        ),
        migrations.CreateModel(
            name='UsageScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField()),
                ('usage_frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='modelauthor',
            name='contact_info',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='modelauthor',
            index=models.Index(fields=['name'], name='models_api__name_0af2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='modelauthor',
            index=models.Index(fields=['rating'], name='models_api__rating_65b2b0_idx'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_uploaded', to='models_api.modelauthor'),
        ),
        migrations.AddField(
            model_name='modelbenchmark',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='models_api.aimodel'),
        ),
        migrations.AddField(
            model_name='modelpurchase',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='models_api.aimodel'),
        ),
        migrations.AddField(
            model_name='usagescenario',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_scenarios', to='models_api.aimodel'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['name'], name='models_api__name_cace83_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['framework', 'model_type'], name='models_api__framewo_28679e_idx'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='models_api_aimodel_unique_model_version'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='models_api_aimodel_price_not_negative'),
        ),
        migrations.AddIndex(
            model_name='modelpurchase',
            index=models.Index(fields=['purchase_date'], name='models_api__purchas_b6b3b6_idx'),
        ),
    ]
